name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          cache: true

      - name: Verify Flutter & Dart Version
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Debug Secret Key Before Build
        run: |
          echo "🔍 Using ENV_SECRET_KEY=${SECRET_KEY}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build Flutter Web with Secret
        run: |
          flutter build web --dart-define=ENV_SECRET_KEY="${SECRET_KEY}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
