jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # Use the correct version that supports Dart 3.5.1
          cache: true  # Caches dependencies for faster builds

      - name: Verify Flutter & Dart Version
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Print Secret (for debugging)
        run: echo "Secret is set"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
