name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # Adjust version as needed
          cache: true  # Cache dependencies for faster builds

      - name: Verify Flutter & Dart Version
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Check if SECRET_KEY is set
        run: |
          if [ -z "$SECRET_KEY" ]; then
            echo "❌ SECRET_KEY is NOT set!" && exit 1
          else
            echo "✅ SECRET_KEY is set"
          fi
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Debug Secret Key
        run: echo "🔍 SECRET_KEY is $SECRET_KEY"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build Flutter Web with Secret
        run: |
          echo "🚀 Building with SECRET_KEY=$SECRET_KEY"
          flutter build web --dart-define=SECRET_KEY=$SECRET_KEY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Upload Flutter Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web
