name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # Adjust version as needed
          cache: true  # Cache dependencies for faster builds

      - name: Verify Flutter & Dart Version
        run: |
          flutter --version
          dart --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Check if SECRET_KEY is set
        run: |
          if [ -z "$SECRET_KEY" ]; then
            echo "SECRET_KEY is not set!" && exit 1
          else
            echo "SECRET_KEY is set"
          fi
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build Flutter Web with Secret
        run: flutter build web --dart-define=SECRET_KEY=$SECRET_KEY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
